### ISSUE TITLE
Impossible to use android and ios plugin in the same process

### ISSUE THREAD

**Issue by Bolik** [SamVerschueren/gulp-cordova#10]
Hi,
is it possible to use andoird and ios plugin in the same gulp pipe? It looks like the changes in process.env PWD produce incorrect behaviour. For example, gulp.src('dist') build incorrect relative path after calling android or ios plugin.

**Comment by SamVerschueren** [comment]
the `android` and plugin returns the `apk` files.

``` js
gulp.src('.cordova')
    .pipe(android())
    .pipe(gulp.dest('builds'));
```

will write the `apk` files in the `builds` directory. The iOS plugin does not do this but it should be refactored.

The best way of dealing with this I guess it writing multiple tasks.

``` js
gulp.task('create', () => {
    return gulp.src('dist')
        .pipe(create());
});

gulp.task('android', ['create'], () => {
    return gulp.src('.cordova')
        .pipe(android())
        .pipe(gulp.dest('apks'));
});

gulp.task('ios', ['create'], () => {
    return gulp.src('.cordova')
        .pipe(ios());
});

gulp.task('build', ['android', 'ios']);
```

I believe something like this should work.
